#!/usr/bin/env node
// Export the item-id whitelist shared by the client and the relay
// (server/shared/item_ids.json). The economy (trade / market / mail) only
// accepts ids listed here, and the server uses the gear metadata for market
// search filters (slot, rarity, name, level).
//
//   node tools/export_item_ids.mjs          # rewrite the JSON
//   node tools/export_item_ids.mjs --check  # exit 1 if the committed JSON is stale
//
// Re-run after adding or renaming gear in src/data/gear.js (or items /
// materials) and commit the result.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'server', 'shared', 'item_ids.json');
// The client bundle can't import from server/ (Vercel doesn't upload it), so keep an identical copy in src/data.
const outClient = path.join(root, 'src', 'data', 'item_ids.json');

const { GEAR } = await import(path.join(root, 'src/data/gear.js'));
const { ITEMS } = await import(path.join(root, 'src/data/items.js'));
const { MATS } = await import(path.join(root, 'src/data/materials.js'));

const sortObj = (o) => Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
const gear = {};
for (const g of Object.values(GEAR)) {
  gear[g.id] = { name: g.name, slot: g.slot, rarity: g.rarity, lvl: g.lvl | 0, price: Math.max(0, Math.round(g.price || 0)) };
}
const doc = {
  version: 1,
  note: 'Generated by tools/export_item_ids.mjs - do not edit by hand.',
  // tradable today: bag gear (progress.inventory). items/mats are whitelisted for future use.
  gear: sortObj(gear),
  items: Object.keys(ITEMS).sort(),
  mats: Object.keys(MATS).sort(),
};
const json = `${JSON.stringify(doc, null, 1)}\n`;

if (process.argv.includes('--check')) {
  for (const f of [out, outClient]) {
    const cur = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : '';
    if (cur !== json) { console.error(`${path.relative(root, f)} is stale: run node tools/export_item_ids.mjs`); process.exit(1); }
  }
  console.log('item_ids.json up to date');
} else {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, json);
  fs.writeFileSync(outClient, json);
  console.log(`wrote ${path.relative(root, out)}: ${Object.keys(gear).length} gear, ${doc.items.length} items, ${doc.mats.length} mats`);
}
